TAD-Treinamento_a_distancia/Models/Historico.cs
using System;
using System.Collections.Generic;
using System.Data.Odbc;
using System.Diagnostics.Eventing.Reader;
using System.Linq;
using System.Web;


namespace TAD_Treinamento_a_distancia.Models
{
    public class Historico
    {
        public string LoginUsuario { get; set; }

        public List<string> Treinamento = new List<string>();
        public List<string> DataHora = new List<string>();
        public List<string> Nome = new List<string>();
        public List<string> Nota = new List<string>();
        

        public void RealizaBusca()
        {
            using (OdbcConnection conexao = ConexaoBd.CreateConnection())
            {
                var login = LoginUsuario;
                const string query = "Select * from Historico where LoginUsuario = ? ORDER BY DataHora DESC;";
                var command = new OdbcCommand(query, conexao);
                command.Parameters.AddWithValue("@Login", login);
                
                conexao.Open();
                var resultado = command.ExecuteReader();

                while (resultado.Read())
                {
                    var a = resultado["Treinamento"].ToString();
                    var b = resultado["DataHora"].ToString();
                    var c = resultado["Nome"].ToString();
                    var d = resultado["Nota"].ToString();

                    GravaDados(a, b, c, d);
                    
                }
            }
        }



        private void GravaDados(string treinamento, string dataHora, string nome, string nota)
        {
            this.Treinamento.Add(treinamento);
            this.DataHora.Add(dataHora);
            this.Nome.Add(nome);
            this.Nota.Add(nota);
        }

    }
}
                    
                

TAD-Treinamento_a_distancia/Controllers/AvaliacaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using TAD_Treinamento_a_distancia.Models;

namespace TAD_Treinamento_a_distancia.Controllers
{
    public class AvaliacaoController : Controller
    {
        //
        // GET: /Avaliacao/

        CarregarAvaliacao c = new CarregarAvaliacao();
        
        
        


        [Authorize]
        [HttpGet]
        public ActionResult Catalogo()
        {
            CarregarTreinamentos carrega = new CarregarTreinamentos();
            carrega.Busca();
            return View(carrega);
        }
        
        [Authorize]
        [HttpPost]
        public ActionResult Catalogo(FormCollection form)
        {
            Session["Curso"] = form["curso"];
            FormsAuthentication.SetAuthCookie(Session.SessionID, false);
             
            return RedirectToAction("Teste", c);
        }


        [Authorize]
        [HttpGet]
        public ActionResult Teste(CarregarAvaliacao c)
        {
            var curso = (string)Session["Curso"];
            c.BuscaEnunciados(curso);
            return View(c);
        }
        [Authorize]
        [HttpPost]
        public ActionResult Teste(FormCollection form)
        {
            for (int i = 0; i < form.Count; i++)
			{
                c.Gabarito.Add(form[i]);
			}

            for (int i = 0; i < c.Gabarito.Count; i++)
            {
			
                var curso = (string)Session["Curso"];
                c.Corrigir(curso, i + 1); 
			}

            var pessoa = (Pessoa)Session["UsuarioAutenticado"];
            var cursos = (string)Session["Curso"];
            c.GravarNota(pessoa, cursos);

            return Redirect("Historico");
        }


        [Authorize]
        public ActionResult Historico()
        {

            var h = new Historico();
            var pessoa = (Pessoa)Session["UsuarioAutenticado"];
            h.LoginUsuario = pessoa.Usuario.Login;
            h.RealizaBusca();

            return View(h);
        }



    }
}

TAD-Treinamento_a_distancia/Views/Avaliacao/Catalogo.cshtml
@using Microsoft.Ajax.Utilities
@model TAD_Treinamento_a_distancia.Models.CarregarTreinamentos

@{
    ViewBag.Title = "Catalogo";
}

@using (@Html.BeginForm("Catalogo", "Avaliacao", FormMethod.Post))
{
    
   
    for (int i = 0; i < @Model.LinkVideo.Count; i++)
    {
        <div id="videos">    
        <fieldset  style="width: 290px; float: left">
            <legend>@Model.Nome[i]</legend>
            <video width="260" height="170" controls>
                <source src="~/Content/themes/base/videos/@Model.LinkVideo[i]" type="video/mp4">
            </video>
            <p>
               
               <button type="submit" id="curso" name="curso" value="@Model.Nome[i]">Realizar Prova</button>
            </p>
        </fieldset>
        </div>

    }

}

TAD-Treinamento_a_distancia/Views/Avaliacao/Historico.cshtml
@model TAD_Treinamento_a_distancia.Models.Historico
@{
    ViewBag.Title = "Historico";
}



<style type="text/css">
      table
      {
        font-family:"Trebuchet MS", Arial, Helvetica, sans-serif;
        width:80%;
        border-collapse:collapse;
        margin: 0 0 0 10% ;
        
      }
      table td, th
      {
        border:1px solid #808080;
        padding:3px 7px 2px 7px;
        
      }
      table th
      {
        font-size:1.2em;
        text-align:center;
        padding-top:5px;
        padding-bottom:4px;
        background-color:#4800ff;
        color:#fff;
      }
      table tr.alt td
      {
        color:#000;
        background-color:#D6EDFF;
      }
      table caption 
      {
       font-size:30px;
      }
    </style>


<table summary="Esta tabela mostra o hitórico dos treinamentos realizados pelo colaborador.">
<caption>Histórico de treinamentos realizados</caption>
<tr>
<th>Data / Hora</th>
<th>Nome Do treinamento</th>
<th>Nome</th>
<th>Nota</th>
</tr>
@for (var i = 0; i < @Model.Nome.Count; i++)
{
<tr>
<td>@Model.DataHora[i]</td>
<td>@Model.Treinamento[i]</td>
<td>@Model.Nome[i]</td>
<td>@Model.Nota[i]</td>
</tr>
}   
</table>

TAD-Treinamento_a_distancia/Views/Avaliacao/Teste.cshtml
@model TAD_Treinamento_a_distancia.Models.CarregarAvaliacao

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Teste</title>
    <link href="~/Content\Site.css" rel="stylesheet" media="screen" />
</head>
<body>
    <div>
        @using (Html.BeginForm("Teste", "Avaliacao", FormMethod.Post))
        {

            <fieldset style="height: 1000px; width:800px; margin-left: 250px">
                <legend>
                    Questionário
                </legend>
                <ol>
                    @for (int i = 0; i < @Model.Enunciados.Count; i++)
                    
                    {
                        <br />
                        <li>@Model.Enunciados[i]</li>
                        <br />
                        string c = (string)Session["Curso"];
                        Model.BuscaAlternativas(c, i+1);
                        <ol style="list-style:lower-alpha">
                            @for (int j = 0; j < @Model.Alternativas.Count; j++)
                            {
                                <li>

                                    @Html.RadioButton("radio" + @i, @Model.Alternativas[j],false) @Model.Alternativas[j]

                                </li>

                            }
                        </ol>

                    }

                </ol>

            </fieldset>
            
            
            <center><button type="submit" style="height:50px ; width:200px; font-size:20px">Finalizar Prova</button></center>
    }
</div>
</body>
</html>